export const SEND_MESSAGE_TO_BOT = "SEND_MESSAGE_TO_BOT";
export const SEND_MESSAGE_TO_BOT_FAIL = "SEND_MESSAGE_TO_BOT_FAIL";

export const RECEIVE_RESPONSE_FROM_BOT = "RECEIVE_RESPONSE_FROM_BOT";
export const RECEIVE_RESPONSE_FROM_BOT_FAIL = "RECEIVE_RESPONSE_FROM_BOT_FAIL";

export const FETCH_USER_CONVERSATIONS = "FETCH_USER_CONVERSATIONS";
export const FETCH_USER_CONVERSATIONS_FAIL = "FETCH_USER_CONVERSATIONS_FAIL";
