export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const GET_USER = "GET_USER";
export const GET_USER_FAIL = "GET_USER_FAIL";
export const GET_USERS = "GET_USERS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";
export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

export const FETCH_USER_PLANTS = "FETCH_USER_PLANTS";
export const FETCH_USER_PLANTS_FAIL = "FETCH_USER_PLANTS_FAIL";

export const FETCH_USER_PLANT = "FETCH_USER_PLANT";
export const FETCH_USER_PLANT_FAIL = "FETCH_USER_PLANT_FAIL";

export const SAVE_CARE_REMINDER = "SAVE_CARE_REMINDER";
export const SAVE_CARE_REMINDER_FAIL = "SAVE_CARE_REMINDER_FAIL";

export const UPDATE_CARE_REMINDER = "UPDATE_CARE_REMINDER";
export const UPDATE_CARE_REMINDER_FAIL = "UPDATE_CARE_REMINDER_FAIL";

export const GET_USER_REMINDER_DATES = "GET_USER_REMINDER_DATES";
export const GET_USER_REMINDER_DATES_FAIL = "GET_USER_REMINDER_DATES_FAIL";

export const GET_USER_REMINDER_DATES_BY_DATE =
  "GET_USER_REMINDER_DATES_BY_DATE";
export const GET_USER_REMINDER_DATES_BY_DATE_FAIL =
  "GET_USER_REMINDER_DATES_BY_DATE_FAIL";

export const UPDATE_REMINDER_COMPLETION_SUCCESS =
  "UPDATE_REMINDER_COMPLETION_SUCCESS";
export const UPDATE_REMINDER_COMPLETION_FAIL =
  "UPDATE_REMINDER_COMPLETION_FAIL";
